GET http://localhost:1234/api/espacios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbnVAZ2FyZG9uIiwiaWF0IjoxNjk5MTUzMjMzLCJleHAiOjE2OTkxNTMyNTN9.YFkpdAej16iBsnexip1OpH_fUUeBQaTa8YWpd1rWU2o

###

DELETE http://localhost:1235/logout
Content-Type: application/json

#Todavia no funciona porque no persistimos los tokens
{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbnVAZ2FyZG9uIiwiaWF0IjoxNjk5MTUzNzUyfQ.mFJTaK8-2B_266f0TJ-wSjhGAx2D1FECgiaK4zycBr0"
}

###

POST http://localhost:1235/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hbnVAZ2FyZG9uIiwiaWF0IjoxNjk5MTUzNzUyfQ.mFJTaK8-2B_266f0TJ-wSjhGAx2D1FECgiaK4zycBr0"
}

###

POST http://localhost:1235/login
Content-Type: application/json

{
    "email":"manu@gardon"
}